//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SnippetDesigner {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VSPackage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VSPackage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SnippetDesigner.VSPackage", typeof(VSPackage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 HARDKDPZCKCQAJPPR1CTMQA0E0QHDTM3KADZPRMMKTA9HQCADRQKD9J8HDIAEIE9PEC2MZQ2DAQQR1PHMZI8A8IAJ1RERTJIK8MKHPQTIRK9EAIKMKQEKKEHDQICK3P9 的本地化字符串。
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snippet Designer 的本地化字符串。
        /// </summary>
        internal static string _100 {
            get {
                return ResourceManager.GetString("100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snippet Designer is a Visual Studio plug in which allows you to create and search for snippets inside the IDE 的本地化字符串。
        /// </summary>
        internal static string _102 {
            get {
                return ResourceManager.GetString("102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string _105 {
            get {
                return ResourceManager.GetString("105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code Snippet 的本地化字符串。
        /// </summary>
        internal static string _106 {
            get {
                return ResourceManager.GetString("106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SnippetFile 的本地化字符串。
        /// </summary>
        internal static string _107 {
            get {
                return ResourceManager.GetString("107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Blank Snippet File 的本地化字符串。
        /// </summary>
        internal static string _109 {
            get {
                return ResourceManager.GetString("109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snippet Designer 的本地化字符串。
        /// </summary>
        internal static string _14340 {
            get {
                return ResourceManager.GetString("14340", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snippet Designer Options 的本地化字符串。
        /// </summary>
        internal static string _16055 {
            get {
                return ResourceManager.GetString("16055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Options 的本地化字符串。
        /// </summary>
        internal static string _17770 {
            get {
                return ResourceManager.GetString("17770", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset  的本地化字符串。
        /// </summary>
        internal static string _17771 {
            get {
                return ResourceManager.GetString("17771", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snippet Replacement Marker 的本地化字符串。
        /// </summary>
        internal static string _200 {
            get {
                return ResourceManager.GetString("200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CSharp Snippets 的本地化字符串。
        /// </summary>
        internal static string _202 {
            get {
                return ResourceManager.GetString("202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VB Snippets 的本地化字符串。
        /// </summary>
        internal static string _203 {
            get {
                return ResourceManager.GetString("203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML Snippets 的本地化字符串。
        /// </summary>
        internal static string _204 {
            get {
                return ResourceManager.GetString("204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _300 {
            get {
                object obj = ResourceManager.GetObject("300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _301 {
            get {
                object obj = ResourceManager.GetObject("301", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon _400 {
            get {
                object obj = ResourceManager.GetObject("400", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon _401 {
            get {
                object obj = ResourceManager.GetObject("401", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon _404 {
            get {
                object obj = ResourceManager.GetObject("404", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _500 {
            get {
                object obj = ResourceManager.GetObject("500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon _600 {
            get {
                object obj = ResourceManager.GetObject("600", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
